### ISSUE TITLE
Basic Code

### ISSUE THREAD

**Issue by abidmalikwaterloo** [lexfridman/deeptraffic#6]
Thanks for the course. I am currently following it. I am new to AI. I want to take part in the competition. Is there some basic running code that I can take and start working on it? Sorry if it is not a relevant question.

**Comment by lexfridman** [comment]
@abidmalikwaterloo Follow the [DeepTraffic basic tutorial documentaiton](https://selfdrivingcars.mit.edu/deeptraffic-documentation/). That should help you get started.

**Comment by psomani16k** [comment]
Docs do not exist
