### ISSUE TITLE
Observation error?

### ISSUE THREAD

**Issue by Shmuma** [lexfridman/deeptraffic#7]
Hi!

From simple investigation of observations passed to the neural network's input, I see very weird values passed having the following issues:

First of all, observation vector contains 0 for cells outside of the road and 1 if cell is not occupyed by other car (those values are not mentioned in arxiv paper).

Second, much more serious problem is related to situations with occupied cells. Ff the cell is occupied by other car, it doesn't have speed relative to the central car (as was stated in the paper), but rather has values between 0.018 and 0.27, regardless of relative speed of the other car. 

Even if my car is constantly issuing decelerate action and all the cars are overtaking me at high speed, this number is positive and has the range above. For example, that's the small log of state vector I'm observing if lanesSide = 3, patchesAhead = 1, patchesBehind = 0, temporal_window = 0 (which gives me just 7 numbers for row in front of the car):

```
VM1698:71 (7) [1, 0.025997055518438162, 1, 1, 1, 1, 1]
VM1698:71 (7) [1, 1, 1, 1, 0.020270829044069006, 1, 1]
VM1698:71 (7) [1, 0.02407384558168598, 1, 1, 1, 1, 1]
VM1698:71 (7) [1, 1, 1, 1, 0.026940491870455902, 1, 1]
VM1698:71 (7) [1, 1, 1, 1, 1, 1, 1]
VM1698:71 (7) [1, 1, 1, 1, 1, 1, 0.02142199183294735]
VM1698:71 (7) [1, 1, 0.018471935100245227, 1, 1, 1, 1]
```
As I've said, those numbers stay positive regardless of relative speed, which looks like a bug and deviates from formula given in the paper.

**Comment by Shmuma** [comment]
Update: from a bit more investigation, looks like all speed put in occupied cells are not relative at all, but just an actual speed of the car at that cell divided by 2000. Even cells occupied by the central car have non-zero values at them.

**Comment by jackft** [comment]
Hey @Shmuma, sorry for any confusion. The values in the cells represent the absolute velocity of the vehicles. They are 0 if the location of a cell is outside the road, the velocity / 2000 if occupied by a vehicle, and 1 otherwise. In the paper, by relative, we were referring to the coordinates of the occupancy grid, i.e., it uses the ego vehicles local coordinate system rather than the global coordinate system of the road.

**Comment by Shmuma** [comment]
@jackft Thanks for clarification!
